FROM registry.access.redhat.com/ubi9/ubi

WORKDIR /app
RUN mkdir -p /data/
ENV DB_PATH=/data/kai_solutions.db

RUN dnf --refresh -y update \
 && dnf -y install cargo gcc gcc-c++ git libffi-devel libpq-devel python3.12-cryptography python3.12-devel python3.12-pip \
 && dnf -y clean all

ENV MATURIN_NO_INSTALL_RUST=true
ENV PIP_FIND_LINKS=/app/hermeto-output/deps/pip/
ENV PIP_NO_INDEX=true
ENV install "pip3.12 install --no-cache-dir ./kai_mcp_solution_server"
